"""Plain-text explanations, counted from the per-category change in category wins
(never generated by a model): "+2 category wins: passes 2 teams in BLK, 1 in FG%;
costs 1 team in 3PM." A half means a tie gained or lost.

pitch_text phrases the same numbers for the OTHER manager in a deal (Offer
Builder's "pitch"): what helps them, then what they give up, so it reads like
something you could paste into league chat -- still counted from the numbers,
never generated by a model."""

import pandas as pd


def _count(n: float) -> str:
    return f"{n:g}"


def _phrase(items: list[tuple[str, float]]) -> str:
    first_label, first_n = items[0]
    noun = "team" if first_n == 1 else "teams"
    parts = [f"{_count(first_n)} {noun} in {first_label}"]
    parts += [f"{_count(n)} in {label}" for label, n in items[1:]]
    return ", ".join(parts)


def explain(cat_delta: pd.Series | dict) -> str:
    """cat_delta: change in category wins per category (column names as index)."""
    deltas = pd.Series(cat_delta, dtype="float64").fillna(0.0)
    total = float(deltas.sum())
    gains = [(c, d) for c, d in deltas.sort_values(ascending=False).items() if d > 0]
    losses = [(c, -d) for c, d in deltas.sort_values().items() if d < 0]
    if not gains and not losses:
        return "No change in category wins."
    noun = "category win" if abs(total) == 1 else "category wins"
    head = f"{total:+g} {noun}" if total else "Even trade-off"
    parts = []
    if gains:
        parts.append("passes " + _phrase(gains))
    if losses:
        parts.append("costs " + _phrase(losses))
    return f"{head}: {'; '.join(parts)}."


def pitch_text(cat_delta: pd.Series | dict) -> str:
    """cat_delta: the OTHER manager's change in category wins per category. Leads
    with what helps them; if they also give something up, says so plainly."""
    deltas = pd.Series(cat_delta, dtype="float64").fillna(0.0)
    gains = [(c, d) for c, d in deltas.sort_values(ascending=False).items() if d > 0]
    losses = [(c, -d) for c, d in deltas.sort_values().items() if d < 0]
    if not gains and not losses:
        return "This doesn't change your category wins either way."
    if not gains:
        return f"This costs you category wins: {_phrase(losses)}."
    text = (
        f"This helps you in {', '.join(label for label, _ in gains)}: you'd pass {_phrase(gains)}."
    )
    text += " You lose nothing." if not losses else f" You'd give up {_phrase(losses)}."
    return text
