"""Plain-text explanations, counted from the per-category change in category wins
(never generated by a model): "+2 category wins: passes 2 teams in BLK, 1 in FG%;
costs 1 team in 3PM." A half means a tie gained or lost."""

import pandas as pd

from categories import COLUMNS, LABELS


def _count(n: float) -> str:
    return f"{n:g}"


def _phrase(items: list[tuple[str, float]]) -> str:
    first_label, first_n = items[0]
    noun = "team" if first_n == 1 else "teams"
    parts = [f"{_count(first_n)} {noun} in {first_label}"]
    parts += [f"{_count(n)} in {label}" for label, n in items[1:]]
    return ", ".join(parts)


def explain(cat_delta: pd.Series | dict) -> str:
    """cat_delta: change in category wins per category (column names as index)."""
    deltas = pd.Series(cat_delta).reindex(COLUMNS).fillna(0.0)
    total = float(deltas.sum())
    gains = [(LABELS[c], d) for c, d in deltas.sort_values(ascending=False).items() if d > 0]
    losses = [(LABELS[c], -d) for c, d in deltas.sort_values().items() if d < 0]
    if not gains and not losses:
        return "No change in category wins."
    noun = "category win" if abs(total) == 1 else "category wins"
    head = f"{total:+g} {noun}" if total else "Even trade-off"
    parts = []
    if gains:
        parts.append("passes " + _phrase(gains))
    if losses:
        parts.append("costs " + _phrase(losses))
    return f"{head}: {'; '.join(parts)}."
